force-app/main/default/objects/JSON_To_Object_Record__e/JSON_To_Object_Record__e.object-meta.xml
<CustomObject>
    <description>This event takes the JSON data as well as the object name. This data is inserted into the ord.</description>
    <label>JSON To Object Record</label>
    <pluralLabel>JSON To Object Records</pluralLabel>
</CustomObject>

force-app/main/default/objects/JSON_To_Object_Record__e/fields/JSON_Data__c.field-meta.xml
<CustomField>
    <fullName>JSON_Data__c</fullName>
    <description>This will hold the inserted JSON Data</description>
    <label>JSON Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/JSON_To_Object_Record__e/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <description>It holds the name of the object</description>
    <label>Object Name</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/JSONToObjectRecordHandlerTest.cls
@isTest
public class JSONToObjectRecordHandlerTest {
    @isTest
    static void testInsertRecordsFromPlatformEvent() {
        // Test with Account (no polymorphic fields)
        String objectName = 'Account';
        String jsonData = '[{"attributes":{"type":"' + objectName + '"},"Name": "Test Account Event"}]';
        JSON_To_Object_Record__e testEvent = new JSON_To_Object_Record__e(
            JSON_Data__c = jsonData,
            Object_Name__c = objectName
        );
        Test.startTest();
        EventBus.publish(testEvent);
        Test.stopTest();

        String query = 'SELECT Id, Name FROM ' + objectName +
                            ' WHERE Name = \'Test Account Event\'';
        List<SObject> insertedRecords = Database.query(query);
        System.assertEquals(1, insertedRecords.size(), 'One ' 
                            + objectName + ' should be inserted');
        System.assertEquals('Test Account Event', insertedRecords[0].get('Name'), 
                                objectName + ' name should match');
    }
}