force-app/main/default/objects/JSON_To_Object_Record__e/JSON_To_Object_Record__e.object-meta.xml
<CustomObject>
    <description>This event takes the JSON data as well as the object name. This data is inserted into the ord.</description>
    <label>JSON To Object Record</label>
    <pluralLabel>JSON To Object Records</pluralLabel>
</CustomObject>

force-app/main/default/objects/JSON_To_Object_Record__e/fields/JSON_Data__c.field-meta.xml
<CustomField>
    <fullName>JSON_Data__c</fullName>
    <description>This will hold the inserted JSON Data</description>
    <label>JSON Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/JSON_To_Object_Record__e/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <description>It holds the name of the object</description>
    <label>Object Name</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Logs__c/Logs__c.object-meta.xml
<CustomObject>
    <description>It contains the records of the error message when a lead record is not inserted.</description>
    <label>Logs</label>
    <nameField>
        <displayFormat>LOG-{0000}</displayFormat>
        <label>Logs ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Logs__c/fields/Error__c.field-meta.xml
<CustomField>
    <fullName>Error__c</fullName>
    <description>It stores the error message generated by the log.</description>
    <label>Error</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/JSONToObjectRecordHandler.cls
public with sharing class JSONToObjectRecordHandler implements Database.Stateful {
    public static List<JSON_To_Object_Record__e> processedEvents = new List<JSON_To_Object_Record__e>();
    public static Set<String> processedEventUuids = new Set<String>();
    public static void processEvents(List<JSON_To_Object_Record__e> events) {
        List<SObject> ObjectList;
        List<Logs__c> errorLogs = new List<Logs__c>();
        for(JSON_To_Object_Record__e e : events) {
            String jsonInput = e.JSON_Data__c;
            String objName = e.Object_Name__c;
            String eventUuid = e.EventUuid;
            if(!processedEventUuids.contains(eventUuid)){
                System.debug('Processing event with eventUuid: ' + eventUuid);
                Map<String, Object> jsonMap = (Map<String, Object>) JSON.deserializeUntyped(jsonInput);
                String dataJson = JSON.serialize(jsonMap.get('data'));
                ObjectList = (List<SObject>) JSON.deserialize(dataJson, List<SObject>.class);
                for(SObject obj : ObjectList){
                    System.debug('Record: ' + obj + ', Object Name: ' + objName + ', EventUuid: ' + eventUuid);
                }
                processedEventUuids.add(eventUuid);
            }
            Database.SaveResult[] results = Database.insert(ObjectList, false);
            for(Database.SaveResult result : results){
                if(result.isSuccess()){
                    System.debug('Successfully upserted Record with Id: ' + result.getId());
                } else {
                    for(Database.Error err : result.getErrors()){
                        Logs__c log = new Logs__c();
                        log.Error__c = err.getMessage();
                        log.Source_Object__c = 'JSON_To_Object_Record__e';
                        errorLogs.add(log);
                    }
                }
            }
            processedEvents.add(e);
        }
        if(!errorLogs.isEmpty()){
            insert errorLogs;
        }
    }
}